# Generated by Django 5.0.6 on 2026-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scoring_type', models.CharField(choices=[('ball_by_ball', 'Ball By Ball'), ('game_set_point', 'Game Set Point')], max_length=50)),
                ('max_players', models.IntegerField(default=0)),
                ('reserve_players', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
