# Generated by Django 6.0.6 on 2026-06-09 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='reserve_players',
        ),
        migrations.AddField(
            model_name='sport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='tiebreak_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='scoring_type',
            field=models.CharField(choices=[('POINTS', 'Points'), ('RUNS', 'Runs'), ('GOALS', 'Goals'), ('SETS', 'Sets'), ('CUSTOM', 'Custom')], max_length=20),
        ),
    ]
