# Generated by Django 6.0.6 on 2026-06-09 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_OWNER', 'Team Owner'), ('SCORER', 'Scorer'), ('COMMENTATOR', 'Commentator'), ('VIEWER', 'Viewer'), ('BROADCAST_MANAGER', 'Broadcast Manager')], default='VIEWER', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='tempuser', max_length=100),
        ),
    ]
